# PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/xiejiawei/GolandProjects/ct-K8S/k8s/platform/data/zk"  #这是主机的地址

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-datalog
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/xiejiawei/GolandProjects/ct-K8S/k8s/platform/data/zk"  #这是主机的地址


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-datalog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi