apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "artemis.fullname" . }}-slave
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
spec:
  serviceName: {{ include "artemis.fullname" . }}-slave
  replicas: {{ .Values.replicas }}
  podManagementPolicy: "Parallel"
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ template "artemis.name" . }}
      release: {{ .Release.Name | quote }}
      component: slave
  template:
    metadata:
      name: {{ include "artemis.fullname" . }}
      annotations:
{{ toYaml .Values.replica.annotations | indent 8 }}
      labels:
        app: {{ template "artemis.name" . }}
        release: {{ .Release.Name | quote }}
        component: slave
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      strategy:
        type: Recreate
      initContainers:
      - name: configure-cluster
        image: {{ template "artemis.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        imagePullSecrets: {{ toYaml .Values.image.pullSecrets }}
        command: ["/bin/sh", "/opt/configure-slave/configure-cluster.sh"]
        volumeMounts:
          - name: config-override
            mountPath: /var/lib/artemis/etc-override
          - name: configure-common
            mountPath: /opt/configure-common
          - name: configure-slave
            mountPath: /opt/configure-slave
      containers:
      - name: {{ include "artemis.fullname" . }}
        image: {{ template "artemis.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: ARTEMIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "artemis.fullname" . }}
              key: artemis-password
        - name: ARTEMIS_USERNAME
          value: {{ default "artemis" .Values.artemisUser | quote }}
        - name: ARTEMIS_PERF_JOURNAL
          value: {{ default "AUTO" .Values.persistence.testJournalPerformance | quote }}
        ports:
        - name: http
          containerPort: 8161
        - name: core
          containerPort: 61616
        - name: amqp
          containerPort: 5672
        - name: jmxexporter
          containerPort: 9404
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        {{- if .Values.useReadinessProbes }}
        readinessProbe:
          tcpSocket:
            port: core
          initialDelaySeconds: 10
          periodSeconds: 10
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/artemis/data
        - name: config-override
          mountPath: /var/lib/artemis/etc-override
        - name: configure-common
          mountPath: /opt/configure-common
        - name: configure-slave
          mountPath: /opt/configure-slave
      volumes:
      - name: config-override
        emptyDir: {}
      - name: configure-common
        configMap:
          name: {{ include "artemis.fullname" . }}-configure-common
      - name: configure-slave
        configMap:
          name: {{ include "artemis.fullname" . }}-configure-slave
      {{- if .Values.persistence.enabled }}
      {{- else }}
      - name: data
        emptyDir: {}
      {{- end -}}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: {{ include "artemis.fullname" . }}
        release: {{ .Release.Name | quote }}
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
      storageClassName:  {{ .Values.persistence.storageClass | quote }}
      {{- end }}
  {{- end -}}
