

services:

  ynhps-config:
    image: 192.168.10.105/pressure-test/ynhps-config:latest
    ports:
      - "8989:8989"
    environment:
      JAVA_OPTS: >
        -Xms256m -Xmx256m

  ynhps-biz-web:
    hostname: ynhps-biz-web
    image: 192.168.10.105/pressure-test/ynhps2-ynhps-biz-web
    networks:
      - ct
    ports:
      - "8080:8080"
      - "18719:18719"
      - "33333:33333"
    environment:
      JAVA_OPTS: >
        -Xms256m -Xmx1024m
        -Ddubbo.application.qos.port=33333

  ynhps-biz-service:
    image: 192.168.10.105/pressure-test/ynhps2-ynhps-biz-service
    ports:
      - "19081:19081"
      - "18718:18718"
      - "33334:33334"
    environment:
      JAVA_OPTS: >
        -Xms256m -Xmx800m
        -Ddubbo.application.qos.port=33334

  ynhps-cognition-service:
    image: 192.168.10.105/pressure-test/ynhps2-ynhps-cognition-service
    ports:
      - "19089:19089"
      - "18717:18717"
      - "33341:33341"
    environment:
      JAVA_OPTS: >
        -Xms256m -Xmx800m
        -Ddubbo.application.qos.port=33341

  ynhps-tp-service:
    image: 192.168.10.105/pressure-test/ynhps2-ynhps-tp-service
    ports:
      - "19082:19082"
      - "18712:18712"
      - "33337:33337"
    environment:
      JAVA_OPTS: >
        -Xms256m -Xmx600m
        -Ddubbo.application.qos.port=33337
    
  yjserver-sys-service:
    image: 192.168.10.105/pressure-test/yjserver-sys-service

    ports:
      - "8088:8088"
    environment:
      JAVA_OPTS: >
        -Xms256M -Xmx1024M -XX:PermSize=256M -XX:MaxNewSize=256M -XX:MaxPermSize=256M -Dprofile=test

  yjserver-sys-inter:
    image: 192.168.10.105/pressure-test/yjserver-sys-inter
    ports:
      - "8096:8096"
    environment:
      JAVA_OPTS: >
        -Xms256M -Xmx1024M -XX:PermSize=256M -XX:MaxNewSize=256M -XX:MaxPermSize=256M -Dprofile=test

networks:
  ct:
    external: true

