apiVersion: apps/v1
kind: Deployment
metadata:
  name: cognition-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cognition-mysql
  template:
    metadata:
      labels:
        app: cognition-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_USER
              value: "cognition"
            - name: MYSQL_PASSWORD
              value: "cog@2021"
            - name: MYSQL_INITDB_SKIP_TZINFO
              value: "Asia/Shanghai"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-conf
              mountPath: /etc/mysql/conf.d
            - name: mysql-logs
              mountPath: /logs
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-pvc
        - name: mysql-conf
          configMap:
            name: mysql-config
        - name: mysql-logs
          emptyDir: {}