apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-xxl-job-admin
  labels:
    app: {{ .Release.Name }}-xxl-job-admin
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-xxl-job-admin
