apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
        - name: activemq
          image: webcenter/activemq:5.14.3
          ports:
            - containerPort: 61616
            - containerPort: 8161
          volumeMounts:
            - name: activemq-data
              mountPath: /data
            - name: activemq-log
              mountPath: /var/log/activemq
          env:
            - name: ACTIVEMQ_ADMIN_LOGIN
              value: "admin"
            - name: ACTIVEMQ_ADMIN_PASSWORD
              value: "admin"
            - name: ACTIVEMQ_CONFIG_MINMEMORY
              value: "512"
            - name: ACTIVEMQ_CONFIG_MAXMEMORY
              value: "2048"
            - name: TZ
              value: "Asia/Shanghai"
#          restartPolicy: Always
      volumes:
        - name: activemq-data
          persistentVolumeClaim:
            claimName: activemq-data-pvc
        - name: activemq-log
          persistentVolumeClaim:
            claimName: activemq-log-pvc
        - name: localtime
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  type: NodePort  # 修改类型为 NodePort UI：http://localhost:32008/
  selector:
    app: activemq
  ports:
    - name: active-tcp1
      protocol: TCP
      port: 61616
      targetPort: 31391
    - name: active-tcp2
      protocol: TCP
      port: 8161
      targetPort: 32008
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activemq-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # 根据需求调整存储大小
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activemq-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # 根据需求调整存储大小