# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.39
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "cognition"
      MYSQL_PASSWORD: "cog@2021"
      MYSQL_INITDB_SKIP_TZINFO: "Asia/Shanghai"
    ports:
      - 33061:3306