services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
#      - "80:80"
#      - "443:443"
      - "9001:9001"

    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    networks:
      - ct

networks:
  ct:
    external: true
